- name: mac setup
  hosts: localhost
  connection: local
  # sudo実行有無：実行なしのためno
  become: no
  # 対象サーバの情報収集：しないのでno
  gather_facts: no
  # タスクの呼び出し
  roles:
    - 02_roles/homebrew
    - 02_roles/homebrew_cask
    - 02_roles/vscode_extension
    